export const categoryList = [
  'All',
  'Auto Maintenance',
  'Cellphone',
  'Eating Out',
  'Education',
  'Electricity',
  'Entertainment',
  'Gifts',
  'Groceries',
  'Health & Wellness',
  'Hobbies',
  'Home Improvement',
  'Home Maintenance',
  'Internet',
  'Miscellaneous',
  'Other',
  'Rent/Mortgage',
  'Shopping',
  'Transportation',
  'Vacation',
  'Water',
];
